### ISSUE TITLE
Strange parameters

### ISSUE THREAD

**Issue by ArseniiPetrovich** [poanetwork/deployment-bridge#13]
What is the reason for setting both of these parameters in user creation directive?    
```
groups: ""
append: yes
```
This will be parsed by ansible like `create users and add no groups to groups that already exists`, which is exactly the default behaviour (without both of these directives). If your aim was to remove all groups from created user then `append` should be set to `no`, otherwise, group names should be provided.

**Comment by phahulin** [comment]
I think it's useful to remove this user from all groups except primary, and so append should be set to `no`. What do you think?

**Comment by ArseniiPetrovich** [comment]
Good point.

**Comment by ArseniiPetrovich** [comment]
Resolved at #15 PR
