### ISSUE TITLE
Read from contracts `deployedAtBlock`to set default value to start from

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/deployment-bridge#29]
https://github.com/poanetwork/bridge-nodejs/issues/7

From that repo.

When you deploy bridge instance, please run a query to Home and Foreign contracts to setup default starting block. No need for rust-bridge, only to bridge-nodejs

**Comment by phahulin** [comment]
Done in https://github.com/poanetwork/deployment-bridge/pull/32
