### ISSUE TITLE
Move definition of bridge branch to defaults folder of repo role

### ISSUE THREAD

**Issue by ArseniiPetrovich** [poanetwork/deployment-bridge#41]
Now in tasks folder of repo role defined old branch (`support-erc20-native-#81`). I propose to define variable instead of hardcoded specification of branch that will be configured in `defaults` folder. It will allow users to easily override repo branch in `group_vars`.

**Comment by phahulin** [comment]
Now the `master` branch should be used. But it's still better to have a separate variable for branch name.

**Comment by akolotov** [comment]
Was addressed as part of https://github.com/poanetwork/deployment-bridge/pull/45
