### ISSUE TITLE
Add rsyslog setup in case logs are not redirected

### ISSUE THREAD

**Issue by ArseniiPetrovich** [poanetwork/deployment-bridge#42]
Ansible should configure `rsyslog` (/etc/rsyslog.conf) in following manner to allow bridge VM to receive traffic in case it is not getting redirected:
```
# provides UDP syslog reception
module(load="imudp")
input(type="imudp" port="514")

# provides TCP syslog reception
module(load="imtcp")
input(type="imtcp" port="514")
```

**Comment by VladimirNovgorodov** [comment]
If you change the rsyslog configuration file in this way, the logs intended for remote log's server will be sent to the local server and collected in /var/log/syslog.  But now we already have log files for each container in the /var/log/docker folder. I think the change will be out.
